build:
  main: cmd/up/main.go
  binary: up
  goos:
    - darwin
    - linux
    - windows
    - freebsd
    - netbsd
    - openbsd
  goarch:
    - amd64
    - 386
changelog:
  filters:
    exclude:
      - '^docs:'
      - '^refactor'
